### ISSUE TITLE
Quick Suggestion

### ISSUE THREAD

**Issue by Vrytikz** [Fortigate/AutoAFK2#14]
First off thank you for making this awesome bot, i do have a suggestion which is to make it choose faster, because of it choosing slow team ups are canceled.

**Comment by Fortigate** [comment]
Thanks!

I'll have a look into optimizing it, it does lots of checks (like 4-5 other buttons) for stability that slow it down every time it checks for the `Join` button that can be causing issues

**Comment by Fortigate** [comment]
https://github.com/Fortigate/AutoAFK2/commit/9f12d8cab64733e3604334a3fd47aae29e61f710 Should fix it, the safety checks only run now if nothing has been found for 5 minutes. I'll run it overnight and check for stability as my internet is very laggy at the moment
