### ISSUE TITLE
pc version

### ISSUE THREAD

**Issue by kikybulin** [Fortigate/AutoAFK2#18]
its work in pc version?

**Comment by Fortigate** [comment]
Unfortunately needs ADB to work and therefor something running Android. It's probably possible to rewrite it for the official PC client using LUA injection but that opens us up to detection and bans

**Comment by Fortigate** [comment]
Closing this one, in theory everything is portable to PC client with some work but using adb and emulators lets you send commands to background windows which is essential for the project and not possible otherwise last time I looked.
