### ISSUE TITLE
Android emulator resolution

### ISSUE THREAD

**Issue by awayfun** [Fortigate/AutoAFK2#20]
The position clicked on the 1920*1080 resolution screen always has a deviation, making it unusable. 

Could you please tell me which Android emulator you are using, and how to set the resolution? Thank you for your help.

**Comment by Fortigate** [comment]
LDplayer 1920x1080 280 DPI
Bluestacks5 1920x1080 24 DPI

Both confirmed working, I had a look in the code and it will scale images to 1920x1080 automatically without checking if they are 16:9 which might cause issues

**Comment by tonyrex11** [comment]
How about Mumuplayer？ thanks for help

**Comment by awayfun** [comment]
Mumuplayer Cannot use the autoAFK2.After many attempts, the resolution is not suitable and can not be used. Only BlueStacks&nbsp;emulators can be used.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fortigate/AutoAFK2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月8日(星期五) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fortigate/AutoAFK2] Android emulator resolution (Issue #20)





 
How about Mumuplayer？ thanks for help

**Comment by tonyrex11** [comment]
> Mumuplayer Cannot use the autoAFK2.After many attempts, the resolution is not suitable and can not be used. Only BlueStacks&nbsp;emulators can be used.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Fortigate/AutoAFK2" ***@***.***&gt;; 发送时间:&nbsp;2024年11月8日(星期五) 中午11:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Fortigate/AutoAFK2] Android emulator resolution (Issue #20) How about Mumuplayer？ thanks for help — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Copy that, thanks a lot!

**Comment by tonyrex11** [comment]
I try LDplayer9 1920x1080 280 DPI.
And i ran autoafk2.exe, but nothing happened. Did I miss something important?
![QQ20241108-155615](https://github.com/user-attachments/assets/40d931a8-8928-47da-9f1b-4d7f9eb5712a)
