### ISSUE TITLE
Cannot run on Vietnam server

### ISSUE THREAD

**Issue by awayfun** [Fortigate/AutoAFK2#23]
Cannot run on Vietnam server

![PixPin_2024-11-14_21-58-59](https://github.com/user-attachments/assets/5e610a8c-ccaa-4d45-9201-81b292c8ef7a)

What do I need to adjust?

**Comment by Fortigate** [comment]
There is the launch flag `--server vn` that will detect the VN version instead as it has a different ID to Global. Easiest way to use it is create a shortcut to AutoAFK2.exe and add it in the 'Target' box under Properties (E.G `\folder\path\autoafk2.exe --server vn`)
