### ISSUE TITLE
Script works with MumuPlayer

### ISSUE THREAD

**Issue by rockneurotiko** [Fortigate/AutoAFK2#24]
Hey! First thanks for the project! It helps with the daily chores and more importantly AFK pushing that it's being really boring this season.

I saw that in the README the compatibility with MumuPlayer is to be confirmed, so I decided to do the setup with MumuPlayer, and it works perfectly, at least the last version it already has ADB enabled on port 7555, so I didn't need to do anything else, just start the emulator, start the game and launch the script 😄

**Comment by Fortigate** [comment]
Amazing, thanks for the info!

**Comment by Fortigate** [comment]
Readme updated
