### ISSUE TITLE
0.9.13 ADB not connecting.

### ISSUE THREAD

**Issue by masterj1337** [Fortigate/AutoAFK2#26]
Latest version shows the following error.

```
15:13:02 Version: 0.9.13
15:13:04 Connection error:
15:13:04 'NoneType' object has no attribute 'shell'
15:13:04 This is usually caused by there being no ADB device present, check port or manually run 'adb devices' to check
```
ADB is starting and _adb devices_ does show the emulator. Old version just fine,

**Comment by Fortigate** [comment]
New version removes the automatic connect and only uses the port set in `settings.ini`, try port 5555 as the first release had it set to 7555 by accident, uploading a new version now

**Comment by masterj1337** [comment]
That did it.
